import { useState } from 'react'
import { type Address, parseEther } from 'viem'
import { motion } from 'framer-motion'
import { 
  AlertTriangle, 
  Plus, 
  Search, 
  ThumbsUp,
  ThumbsDown,
  Clock,
  CheckCircle,
  XCircle,
  Flag,
  ExternalLink,
  Calendar,
  User,
  Coins,
  Award
} from 'lucide-react'
import { useAppStore } from '../store/appStore'
import { formatDate, formatEther, formatAddress } from '../utils/formatters'
import { ViolationType, ReportStatus } from '../types/global'
import type { IPReport } from '../types/global'
import { uploadTextToIPFS } from '../utils/uploadToIpfs'
import { client } from '../utils/config'

// Mock data for demonstration
const mockReports: IPReport[] = [
  {
    id: '1',
    reporterAddress: '0x1234567890123456789012345678901234567890',
    reportedIPId: 'ip-001',
    violationType: ViolationType.COPYRIGHT_INFRINGEMENT,
    description: 'This artwork appears to be a direct copy of my original piece published on Instagram last month.',
    evidenceUrls: ['https://example.com/evidence1.jpg', 'https://example.com/evidence2.jpg'],
    status: ReportStatus.VOTING,
    votes: [
      {
        id: 'v1',
        voterAddress: '0x2345678901234567890123456789012345678901',
        reportId: '1',
        vote: true,
        stakedAmount: BigInt('1000000000000000000'), // 1 token
        reasoning: 'Clear evidence of copyright infringement',
        createdAt: new Date('2024-03-20T10:00:00Z'),
      },
      {
        id: 'v2',
        voterAddress: '0x3456789012345678901234567890123456789012',
        reportId: '1',
        vote: false,
        stakedAmount: BigInt('500000000000000000'), // 0.5 tokens
        reasoning: 'Not enough evidence to prove infringement',
        createdAt: new Date('2024-03-20T11:00:00Z'),
      },
    ],
    stakedAmount: BigInt('5000000000000000000'), // 5 tokens
    createdAt: new Date('2024-03-19T14:30:00Z'),
  },
  {
    id: '2',
    reporterAddress: '0x2345678901234567890123456789012345678901',
    reportedIPId: 'ip-002',
    violationType: ViolationType.AI_GENERATED_FRAUD,
    description: 'This image is generated by AI but being sold as original human artwork.',
    evidenceUrls: ['https://example.com/ai-detection.json'],
    status: ReportStatus.RESOLVED_VALID,
    votes: [],
    stakedAmount: BigInt('3000000000000000000'), // 3 tokens
    createdAt: new Date('2024-03-18T09:15:00Z'),
    resolvedAt: new Date('2024-03-20T16:45:00Z'),
  },
  {
    id: '3',
    reporterAddress: '0x3456789012345678901234567890123456789012',
    reportedIPId: 'ip-003',
    violationType: ViolationType.MEME_THEFT,
    description: 'Popular meme reposted without attribution or permission from original creator.',
    evidenceUrls: ['https://example.com/original-meme.jpg'],
    status: ReportStatus.PENDING,
    votes: [],
    stakedAmount: BigInt('2000000000000000000'), // 2 tokens
    createdAt: new Date('2024-03-21T08:20:00Z'),
  },
]

const violationTypes = Object.values(ViolationType)
const reportStatuses = Object.values(ReportStatus)

export default function Reports() {
  const { searchQuery, setSearchQuery } = useAppStore()
  const [selectedTab, setSelectedTab] = useState<'all' | 'my-reports' | 'my-votes'>('all')
  const [selectedStatus, setSelectedStatus] = useState<string>('all')
  const [selectedType, setSelectedType] = useState<string>('all')
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [reports] = useState<IPReport[]>(mockReports)

  const filteredReports = reports.filter(report => {
    if (selectedStatus !== 'all' && report.status !== selectedStatus) return false
    if (selectedType !== 'all' && report.violationType !== selectedType) return false
    if (searchQuery && !report.description.toLowerCase().includes(searchQuery.toLowerCase())) return false
    return true
  })

  const getStatusIcon = (status: ReportStatus) => {
    switch (status) {
      case ReportStatus.PENDING:
        return <Clock className="h-4 w-4 text-warning-500" />
      case ReportStatus.VOTING:
        return <Flag className="h-4 w-4 text-primary" />
      case ReportStatus.RESOLVED_VALID:
        return <CheckCircle className="h-4 w-4 text-success-500" />
      case ReportStatus.RESOLVED_INVALID:
        return <XCircle className="h-4 w-4 text-error-500" />
      default:
        return <AlertTriangle className="h-4 w-4 text-warning-500" />
    }
  }

  const getStatusColor = (status: ReportStatus) => {
    switch (status) {
      case ReportStatus.PENDING:
        return 'bg-warning-100 text-warning-800'
      case ReportStatus.VOTING:
        return 'bg-primary/10 text-primary'
      case ReportStatus.RESOLVED_VALID:
        return 'bg-success-100 text-success-800'
      case ReportStatus.RESOLVED_INVALID:
        return 'bg-error-100 text-error-800'
      default:
        return 'bg-muted text-muted-foreground'
    }
  }

  const handleCreateReport = async(IP_ID: Address, EVIDENCE: string, bond: string) => {
    const disputeHash = await uploadTextToIPFS(EVIDENCE)
    console.log(`Dispute evidence uploaded to IPFS: ${disputeHash}`)

    // Raise a Dispute
    const disputeResponse = await client.dispute.raiseDispute({
        targetIpId: IP_ID,
        cid: disputeHash,
        targetTag: 'IMPROPER_REGISTRATION',
        bond: parseEther(bond),
        liveness: 2592000, // 30 days
        txOptions: { waitForTransaction: true },
    } as any)
    console.log(`Dispute raised at transaction hash ${disputeResponse.txHash}, Dispute ID: ${disputeResponse.disputeId}`)
  }

  const handleVote = (reportId: string, vote: boolean) => {
    console.log('Voting on report:', reportId, 'Vote:', vote)
  }

  const handleStakeOnReport = (reportId: string) => {
    console.log('Staking on report:', reportId)
  }

  return (
    <div className="max-w-7xl mx-auto">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center justify-between mb-8"
      >
        <div>
          <h1 className="text-3xl font-bold gradient-text mb-4">IP Violation Reports</h1>
          <p className="text-muted-foreground">
            Report and review intellectual property violations in the community
          </p>
        </div>
        <button
          onClick={() => setShowCreateModal(true)}
          className="btn btn-default btn-lg"
        >
          <Plus className="h-5 w-5 mr-2" />
          Submit Report
        </button>
      </motion.div>

      {/* Tabs */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="border-b border-border mb-6"
      >
        <nav className="flex space-x-8">
          {[
            { id: 'all', label: 'All Reports', count: reports.length },
            { id: 'my-reports', label: 'My Reports', count: 2 },
            { id: 'my-votes', label: 'My Votes', count: 5 },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setSelectedTab(tab.id as any)}
              className={`py-4 px-1 border-b-2 font-medium text-sm transition-colors ${
                selectedTab === tab.id
                  ? 'border-primary text-primary'
                  : 'border-transparent text-muted-foreground hover:text-foreground'
              }`}
            >
              {tab.label}
              <span className="ml-2 bg-muted text-muted-foreground px-2 py-1 rounded-full text-xs">
                {tab.count}
              </span>
            </button>
          ))}
        </nav>
      </motion.div>

      {/* Filters */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="bg-card rounded-xl p-6 shadow-sm border mb-8"
      >
        <div className="flex flex-col lg:flex-row gap-4">
          {/* Search */}
          <div className="flex-1">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground h-4 w-4" />
              <input
                type="text"
                placeholder="Search reports..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="input pl-10 w-full"
              />
            </div>
          </div>

          {/* Status Filter */}
          <div className="lg:w-48">
            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              className="input w-full"
            >
              <option value="all">All Statuses</option>
              {reportStatuses.map((status) => (
                <option key={status} value={status}>
                  {status.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
                </option>
              ))}
            </select>
          </div>

          {/* Type Filter */}
          <div className="lg:w-48">
            <select
              value={selectedType}
              onChange={(e) => setSelectedType(e.target.value)}
              className="input w-full"
            >
              <option value="all">All Types</option>
              {violationTypes.map((type) => (
                <option key={type} value={type}>
                  {type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
                </option>
              ))}
            </select>
          </div>
        </div>
      </motion.div>

      {/* Reports List */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3 }}
        className="space-y-6"
      >
        {filteredReports.map((report, index) => (
          <motion.div
            key={report.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="card p-6 hover:shadow-lg transition-all duration-300"
          >
            <div className="flex items-start justify-between mb-4">
              <div className="flex items-start space-x-4">
                <div className="p-3 bg-error-100 rounded-lg">
                  <AlertTriangle className="h-6 w-6 text-error-600" />
                </div>
                <div>
                  <div className="flex items-center space-x-2 mb-2">
                    <h3 className="text-lg font-semibold">
                      {report.violationType.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
                    </h3>
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(report.status)}`}>
                      {getStatusIcon(report.status)}
                      <span className="ml-1">{report.status.replace(/_/g, ' ')}</span>
                    </span>
                  </div>
                  <p className="text-muted-foreground mb-3">{report.description}</p>
                  <div className="flex items-center space-x-4 text-sm text-muted-foreground">
                    <div className="flex items-center">
                      <User className="h-4 w-4 mr-1" />
                      {formatAddress(report.reporterAddress)}
                    </div>
                    <div className="flex items-center">
                      <Calendar className="h-4 w-4 mr-1" />
                      {formatDate(report.createdAt)}
                    </div>
                    <div className="flex items-center">
                      <Coins className="h-4 w-4 mr-1" />
                      {formatEther(report.stakedAmount, 2)} staked
                    </div>
                  </div>
                </div>
              </div>
              <button className="btn btn-ghost btn-sm">
                <ExternalLink className="h-4 w-4" />
              </button>
            </div>

            {/* Evidence */}
            {report.evidenceUrls.length > 0 && (
              <div className="mb-4">
                <h4 className="text-sm font-medium text-foreground mb-2">Evidence:</h4>
                <div className="flex flex-wrap gap-2">
                  {report.evidenceUrls.map((url, idx) => (
                    <a
                      key={idx}
                      href={url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center text-xs bg-accent/20 text-accent-foreground px-2 py-1 rounded hover:bg-accent/30 transition-colors"
                    >
                      <ExternalLink className="h-3 w-3 mr-1" />
                      Evidence {idx + 1}
                    </a>
                  ))}
                </div>
              </div>
            )}

            {/* Voting Section */}
            {report.status === ReportStatus.VOTING && (
              <div className="border-t border-border pt-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-sm font-medium text-foreground mb-2">Community Voting</h4>
                    <div className="flex items-center space-x-4 text-sm">
                      <span className="text-success-600">
                        {report.votes.filter(v => v.vote).length} Valid votes
                      </span>
                      <span className="text-error-600">
                        {report.votes.filter(v => !v.vote).length} Invalid votes
                      </span>
                    </div>
                  </div>
                  <div className="flex items-center space-x-2">
                    <button
                      onClick={() => handleVote(report.id, false)}
                      className="btn btn-outline btn-sm"
                    >
                      <ThumbsDown className="h-4 w-4 mr-2" />
                      Invalid
                    </button>
                    <button
                      onClick={() => handleVote(report.id, true)}
                      className="btn btn-default btn-sm"
                    >
                      <ThumbsUp className="h-4 w-4 mr-2" />
                      Valid
                    </button>
                    <button
                      onClick={() => handleStakeOnReport(report.id)}
                      className="btn btn-secondary btn-sm"
                    >
                      <Award className="h-4 w-4 mr-2" />
                      Stake
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Votes Display */}
            {report.votes.length > 0 && (
              <div className="border-t border-border pt-4 mt-4">
                <h4 className="text-sm font-medium text-foreground mb-3">Recent Votes</h4>
                <div className="space-y-2">
                  {report.votes.slice(0, 3).map((vote) => (
                    <div key={vote.id} className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                      <div className="flex items-center space-x-3">
                        <div className={`p-1 rounded-full ${vote.vote ? 'bg-success-100' : 'bg-error-100'}`}>
                          {vote.vote ? (
                            <ThumbsUp className="h-3 w-3 text-success-600" />
                          ) : (
                            <ThumbsDown className="h-3 w-3 text-error-600" />
                          )}
                        </div>
                        <div>
                          <p className="text-sm font-medium">{formatAddress(vote.voterAddress)}</p>
                          {vote.reasoning && (
                            <p className="text-xs text-muted-foreground">{vote.reasoning}</p>
                          )}
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="text-sm font-medium">{formatEther(vote.stakedAmount, 2)} tokens</p>
                        <p className="text-xs text-muted-foreground">{formatDate(vote.createdAt)}</p>
                      </div>
                    </div>
                  ))}
                  {report.votes.length > 3 && (
                    <button className="text-sm text-primary hover:text-primary/80 transition-colors">
                      View all {report.votes.length} votes
                    </button>
                  )}
                </div>
              </div>
            )}
          </motion.div>
        ))}

        {filteredReports.length === 0 && (
          <div className="text-center py-12">
            <AlertTriangle className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-medium text-foreground mb-2">No reports found</h3>
            <p className="text-muted-foreground">
              Try adjusting your filters or submit a new report.
            </p>
          </div>
        )}
      </motion.div>

      {/* Create Report Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-card rounded-xl p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto"
          >
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-semibold">Submit IP Violation Report</h2>
              <button
                onClick={() => setShowCreateModal(false)}
                className="btn btn-ghost btn-sm"
              >
                ×
              </button>
            </div>

            <form className="space-y-6">
              <div>
                <label className="label">Violation Type</label>
                <select className="input w-full">
                  {violationTypes.map((type) => (
                    <option key={type} value={type}>
                      {type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="label">IP Asset ID</label>
                <input
                  type="text"
                  className="input w-full"
                  placeholder="Enter the IP asset ID that violates your rights"
                />
              </div>

              <div>
                <label className="label">Description</label>
                <textarea
                  className="textarea w-full"
                  rows={4}
                  placeholder="Provide a detailed description of the violation..."
                />
              </div>

              <div>
                <label className="label">Evidence URLs</label>
                <textarea
                  className="textarea w-full"
                  rows={3}
                  placeholder="Provide URLs to evidence (one per line)"
                />
              </div>

              <div>
                <label className="label">Stake Amount (tokens)</label>
                <input
                  type="number"
                  className="input w-full"
                  placeholder="Amount to stake on this report"
                  min="0"
                  step="0.1"
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Higher stakes increase report credibility but involve more risk
                </p>
              </div>

              <div className="flex items-center justify-end space-x-3">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="btn btn-outline"
                >
                  Cancel
                </button>
                <button type="submit" className="btn btn-default" onClick={() => handleCreateReport}>
                  Submit Report
                </button>
              </div>
            </form>
          </motion.div>
        </div>
      )}
    </div>
  )
}